name: My First Workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
  
      - name: Welcome Message
        run: |
          echo "My first github actions job"
          ls
          cat README.md

      - name: Installing Coway
        run: sudo apt-get install cowsay -y
      
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "RAWRRR" > dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file
          path: ./dragon.txt

  second-job:
    needs: first_job
    runs-on: ubuntu-latest
    concurrency:
        group: prod-deployment
        cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      
      - name: Download artifact v3
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

      - name: Display Dragon
        run: cat dragon.txt