name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
  
      - name: Welcome Message
        run: |
          echo "My first github actions job"
          ls
          cat README.md
      
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "RAWRRR" > dragon.txt
        
      # - name: List Files
      #   run: ls

      # - name: Read file
      #   run: cat README.md